version: '3.9'

services:
  node-api:
    image: ghcr.io/magloiredaniel/cicd-projet2-github-action-docker/node-api:latest
    pull_policy: always
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/magloiredaniel/cicd-projet2-github-action-docker/frontend:latest
    pull_policy: always
    ports:
      - target: 8081
        published: 80
    restart: always
