name: 'Déployer sur le serveur cible'
description: 'Effectue un déploiement sur le serveur cible'
inputs:
  token_github:
    description: 'Clé ssh pour notre server VPS'
    required: true
  server_stag_ip:
    description: 'Adresse IP de notre serveur cible VPS'
    required: true
  server_prod_ip:
    description: 'Adresse IP de notre serveur cible VPS'
    required: true
  user_vps:
    description: 'user for connexion sur notre VPS'
    default: root
  vps_key:
    description: 'Clé secrète pour l authentification SSH du server de staging'
    required: true
  vps_prod_key:
    description: 'Clé secrète pour l authentification SSH du server de production'
    required: true
runs:
  using: 'composite'
  steps:
    # - name: déployer sur le serveur
    #   shell: bash
    #   run: |
    #     eval $(ssh-agent -s)
    #     ssh-add - <<< "${{ inputs.vps_key }}"
    #     mkdir -p ~/.ssh
    #     ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
    #     scp -r docker-compose.prod.yml root@${{ inputs.server_ip }}:/root/docker-compose.prod.yml
    #     ssh root@${{ inputs.server_ip }} "docker login ghcr.io -u ${{ github.actor }} -p ${{ inputs.token_github }} && docker compose -f /root/docker-compose.prod.yml up -d --force-recreate"


    - name: déployer sur le server VPS cible
      shell: bash
      run: |
        eval $(ssh-agent -s)
        ssh-add - <<< "${{ inputs.vps_key }}"
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
        scp docker-compose.prod.yml ${{ inputs.user_vps }}@${{ inputs.server_ip }}:/root/docker-compose.prod.yml
        ssh ${{ inputs.user_vps }}@${{ inputs.server_ip }} "docker login ghcr.io -u ${{ github.actor }} -p ${{ inputs.token_github }} && docker compose -f /root/docker-compose.prod.yml up -d --force-recreate"