name: CI/CD Workflow !!

on: push
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

#QEMU va nous permettre d'émuler un certains nombre de choses. Achitecture, bios, ram, etc
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

#Buildx est ici comme on tape la commande docker build, elle va nous construire l'image.continue-on-error: 
#Buildx c'est une variante de docker build avec des fonctionnalités supplémentaires
      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/magloiredaniel/cicd-projet2-github-action-docker/frontend:latest
