name: CI/CD Workflow !!

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  build-frontend-and-node-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context_name: ./frontend
            image_name_ghcr: ghcr.io/magloiredaniel/cicd-projet2-github-action-docker/frontend
            # image_name_hub: ${{ secrets.DOCKERHUB_USERNAME }}/github-app/cicd-projet2-github-action-docker/frontend
          - context: ./node-api
            image_name_ghcr: ghcr.io/magloiredaniel/cicd-projet2-github-action-docker/node-ap
            # image_name_hub: ${{ secrets.DOCKERHUB_USERNAME }}/github-app/cicd-projet2-github-action-docker/node-ap
    permissions:
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image_name_ghcr }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker Hub
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ${{ matrix.context_mane }}
      #     push: true
      #     tags: ${{ matrix.image_name_hub }}:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context_name }}
          push: true
          tags: ${{ matrix.image_name_ghcr }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
